### ISSUE TITLE
Support Julia LTS?

### ISSUE THREAD

**Issue by chriselrod** [JuliaSIMD/VectorizedStatistics.jl#21]
Why have the lower bound 1.6?

I  dropped 1.8 for StrideArrays here:
https://github.com/JuliaSIMD/StrideArrays.jl/pull/64
but I'm curious why this is necessary.

**Comment by brenhinkeller** [comment]
Ah, so we were at 1.5 traditionally, but I upped it to 1.8 last release so we could use SnoopPrecompile, which IIUC requires 1.8+. 

We could probably just put the SnoopPrecompile block behind a `@static if VERSION` though to support older versions though if you like?

**Comment by brenhinkeller** [comment]
(incidentally, SnoopPrecompile pretty much eliminates our TTFX even before switching to Valentin's native code caching branch!)

**Comment by brenhinkeller** [comment]
Though looks like maybe I was misunderstanding the bounds on SnoopPrecompile?
